pub mod table_upload;
pub mod table_label;
pub mod table_credit;
pub mod table_installment;
pub mod table_installment_items;
pub mod table_cash;
pub mod table_credit_dashboard;
pub mod table_net_dashboard;
pub mod table_cash_credit_dashboard;